version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: website-movie-postgres
    environment:
      POSTGRES_DB: website-movie
      POSTGRES_USER: arata
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
